AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys a VPC with 1 private and 2 public subnets spread over 3 Availability Zones. The public subnets have a route to an internet gateway. The private subnet has a route out to the internet via a NAT Gateway.

Parameters:
  VpcCidr:
    Type: String
    Default: 192.168.0.0/16

  PublicSubnet1CIDR:
    Description: CIDR notation for subnet IP range.
    Type: String
    Default: 192.168.1.0/24

  PublicSubnet2CIDR:
    Description: CIDR notation for subnet IP range.
    Type: String
    Default: 192.168.2.0/24

  PrivateSubnet1CIDR:
    Description: CIDR notation for subnet IP range.
    Type: String
    Default: 192.168.11.0/24

  EnvironmentName:
    Type: String
    Description: Name of the environment which will be prefixed to all resources.

Resources:
  devVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Vpc

  publicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: True
      VpcId: !Ref devVpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet1

  publicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: True
      VpcId: !Ref devVpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet2

  privateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: False
      VpcId: !Ref devVpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateSubnet1

  devInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-IGW

  igwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref devInternetGateway
      VpcId: !Ref devVpc

  natGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt natGatewayEIP.AllocationId
      SubnetId: !Ref publicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-NatGW
    DependsOn: natGatewayEIP

  natGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  publicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref devVpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicRouteTable

  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref publicRouteTable
      SubnetId: !Ref publicSubnet1

  publicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref publicRouteTable
      SubnetId: !Ref publicSubnet2

  publicRouteDefault:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref publicRouteTable
      GatewayId: !Ref devInternetGateway
    DependsOn: publicRouteTable

  privateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref devVpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateRouteTable

  privateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:  !Ref privateRouteTable
      SubnetId: !Ref privateSubnet1

  privateRouteDefault:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref privateRouteTable
      NatGatewayId: !Ref natGateway
    DependsOn: privateRouteTable


Outputs:
  vpcId:
    Description: VPC output for cross stack referencing. Exports the VPC ID.
    Value: !Ref devVpc
    Export:
      Name: !Sub '${AWS::StackName}-VpcID'

  publicSubnet1:
    Description: Reference to public subnet in AZ1. Exports the subnet ID.
    Value: !Ref publicSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-publicSubnet1'

  publicSubnet2:
    Description: Reference to public subnet in AZ2. Exports the subnet ID.
    Value: !Ref publicSubnet2
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet2'

  privateSubnet1:
    Description: Reference to private subnet in AZ. Exports the subnet ID.
    Value: !Ref privateSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-privateSubnet'
